"""Default constants for VectorForge configuration."""

# --- Database ---
DEFAULT_DB_HOST = "localhost"
DEFAULT_DB_PORT = 5432
DEFAULT_DB_DATABASE = "vectorforge"
DEFAULT_DB_USER = "vectorforge"
DEFAULT_DB_POOL_SIZE = 10
DEFAULT_DB_MAX_OVERFLOW = 5

# --- Storage ---
DEFAULT_STORAGE_BACKEND = "pg"
DEFAULT_STORAGE_THRESHOLD_MB = 10
DEFAULT_S3_REGION = "eu-central-1"

# --- Embedding ---
DEFAULT_EMBEDDING_PROVIDER = "voyage"
DEFAULT_EMBEDDING_MODEL = "voyage-3"
DEFAULT_EMBEDDING_DIMENSIONS = 1024
DEFAULT_EMBEDDING_BATCH_SIZE = 100

# --- Chunking ---
DEFAULT_CHUNKING_STRATEGY = "recursive"
DEFAULT_CHUNK_SIZE = 1000
DEFAULT_CHUNK_OVERLAP = 200
DEFAULT_BREAKPOINT_THRESHOLD = 0.5

# --- LLM ---
DEFAULT_LLM_PROVIDER = "openai"
DEFAULT_LLM_MODEL = "gpt-4o"
DEFAULT_LLM_TEMPERATURE = 0.7
DEFAULT_LLM_MAX_TOKENS = 2048

# --- Monitoring ---
DEFAULT_LOG_LEVEL: str = "INFO"
DEFAULT_LOG_FORMAT: str = "json"
DEFAULT_METRICS_FLUSH_INTERVAL_SECONDS = 60
DEFAULT_HEALTH_CHECK_TIMEOUT_SECONDS = 5
